/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AssistanceRequest {
  'id' : bigint,
  'status' : AssistanceStatus,
  'paymentMethod' : string,
  'userEmail' : string,
  'country' : string,
  'fullName' : string,
  'description' : string,
  'submissionDate' : Time,
  'amountRequested' : string,
  'accountDetails' : string,
  'reason' : string,
}
export type AssistanceStatus = { 'pending' : null } |
  { 'underReview' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export type Time = bigint;
export interface User {
  'id' : Principal,
  'os' : string,
  'password' : string,
  'fullName' : string,
  'email' : string,
  'countryCode' : string,
  'countryName' : string,
  'deviceType' : string,
  'browser' : string,
  'registrationDate' : Time,
  'phoneNumber' : string,
  'ipAddress' : string,
}
export interface UserProfile {
  'fullName' : string,
  'email' : string,
  'countryCode' : string,
  'countryName' : string,
  'phoneNumber' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'adminGetAllRequests' : ActorMethod<
    [string, string],
    Array<AssistanceRequest>
  >,
  'adminGetAllUsers' : ActorMethod<[string, string], Array<User>>,
  'adminGetTotalUserCount' : ActorMethod<[string, string], bigint>,
  'adminLogin' : ActorMethod<[string, string], boolean>,
  'adminUpdateRequestStatus' : ActorMethod<
    [string, string, bigint, AssistanceStatus],
    undefined
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUserRequestsByEmail' : ActorMethod<
    [string, string],
    Array<AssistanceRequest>
  >,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'loginUser' : ActorMethod<[string, string], boolean>,
  'registerUser' : ActorMethod<
    [
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
    ],
    undefined
  >,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitAssistanceRequest' : ActorMethod<
    [string, string, string, string, string, string, string, string],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];