/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const AssistanceStatus = IDL.Variant({
  'pending' : IDL.Null,
  'underReview' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const Time = IDL.Int;
export const AssistanceRequest = IDL.Record({
  'id' : IDL.Nat,
  'status' : AssistanceStatus,
  'paymentMethod' : IDL.Text,
  'userEmail' : IDL.Text,
  'country' : IDL.Text,
  'fullName' : IDL.Text,
  'description' : IDL.Text,
  'submissionDate' : Time,
  'amountRequested' : IDL.Text,
  'accountDetails' : IDL.Text,
  'reason' : IDL.Text,
});
export const User = IDL.Record({
  'id' : IDL.Principal,
  'os' : IDL.Text,
  'password' : IDL.Text,
  'fullName' : IDL.Text,
  'email' : IDL.Text,
  'countryCode' : IDL.Text,
  'countryName' : IDL.Text,
  'deviceType' : IDL.Text,
  'browser' : IDL.Text,
  'registrationDate' : Time,
  'phoneNumber' : IDL.Text,
  'ipAddress' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'fullName' : IDL.Text,
  'email' : IDL.Text,
  'countryCode' : IDL.Text,
  'countryName' : IDL.Text,
  'phoneNumber' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'adminGetAllRequests' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Vec(AssistanceRequest)],
      ['query'],
    ),
  'adminGetAllUsers' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Vec(User)],
      ['query'],
    ),
  'adminGetTotalUserCount' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Nat],
      ['query'],
    ),
  'adminLogin' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], ['query']),
  'adminUpdateRequestStatus' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, AssistanceStatus],
      [],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserRequestsByEmail' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Vec(AssistanceRequest)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'loginUser' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], ['query']),
  'registerUser' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
      ],
      [],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitAssistanceRequest' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
      ],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const AssistanceStatus = IDL.Variant({
    'pending' : IDL.Null,
    'underReview' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const Time = IDL.Int;
  const AssistanceRequest = IDL.Record({
    'id' : IDL.Nat,
    'status' : AssistanceStatus,
    'paymentMethod' : IDL.Text,
    'userEmail' : IDL.Text,
    'country' : IDL.Text,
    'fullName' : IDL.Text,
    'description' : IDL.Text,
    'submissionDate' : Time,
    'amountRequested' : IDL.Text,
    'accountDetails' : IDL.Text,
    'reason' : IDL.Text,
  });
  const User = IDL.Record({
    'id' : IDL.Principal,
    'os' : IDL.Text,
    'password' : IDL.Text,
    'fullName' : IDL.Text,
    'email' : IDL.Text,
    'countryCode' : IDL.Text,
    'countryName' : IDL.Text,
    'deviceType' : IDL.Text,
    'browser' : IDL.Text,
    'registrationDate' : Time,
    'phoneNumber' : IDL.Text,
    'ipAddress' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'fullName' : IDL.Text,
    'email' : IDL.Text,
    'countryCode' : IDL.Text,
    'countryName' : IDL.Text,
    'phoneNumber' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'adminGetAllRequests' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Vec(AssistanceRequest)],
        ['query'],
      ),
    'adminGetAllUsers' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Vec(User)],
        ['query'],
      ),
    'adminGetTotalUserCount' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Nat],
        ['query'],
      ),
    'adminLogin' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], ['query']),
    'adminUpdateRequestStatus' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, AssistanceStatus],
        [],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserRequestsByEmail' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Vec(AssistanceRequest)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'loginUser' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], ['query']),
    'registerUser' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
        ],
        [],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitAssistanceRequest' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };